<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TessitoreGM.Core\TessitoreGM.Core.csproj" />
    <ProjectReference Include="..\TessitoreGM.Events\TessitoreGM.Events.csproj" />
    <ProjectReference Include="..\TessitoreGM.World\TessitoreGM.World.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
