namespace TessitoreGM.Gm;

internal static class DashboardStyles
{
    public const string Content = @"
:root{color-scheme:dark;--ink:#f4efe3;--muted:#aaa393;--panel:rgba(31,35,32,.84);--line:rgba(226,210,176,.16);--gold:#d9b46f}
*{box-sizing:border-box}body{margin:0;min-height:100vh;color:var(--ink);background:radial-gradient(circle at 85% 5%,rgba(143,174,145,.14),transparent 32rem),radial-gradient(circle at 8% 30%,rgba(217,180,111,.1),transparent 28rem),#111512;font-family:Inter,ui-sans-serif,system-ui,sans-serif}
.shell{width:min(1160px,calc(100% - 32px));margin:auto;padding:48px 0 32px}.hero{display:flex;justify-content:space-between;align-items:end;gap:24px;margin-bottom:32px}.eyebrow{margin:0 0 8px;color:var(--gold);font-size:.72rem;font-weight:800;letter-spacing:.18em;text-transform:uppercase}
h1,h2,h3,p{margin-top:0}h1,h2,h3{font-family:Georgia,serif;font-weight:500}h1{margin-bottom:10px;font-size:clamp(2.5rem,7vw,5.5rem);line-height:.95;letter-spacing:-.04em}h2{margin-bottom:0;font-size:2rem}h3{margin-bottom:0;font-size:1.55rem}.lede,.empty-state>p{color:var(--muted);max-width:46rem;line-height:1.6}
button{border:1px solid var(--gold);border-radius:999px;padding:12px 20px;color:#15130d;background:var(--gold);font:inherit;font-weight:800;cursor:pointer}.secondary{color:var(--gold);background:transparent}
.campaign-control{display:flex;justify-content:space-between;align-items:end;gap:24px;padding:24px;border:1px solid var(--line);border-radius:18px;background:rgba(143,174,145,.07)}.campaign-control p{margin-bottom:0;color:var(--muted)}.campaign-forms{display:grid;grid-template-columns:1fr 1fr;gap:12px;min-width:min(100%,520px)}.campaign-forms form{display:grid;gap:8px}.campaign-control label{color:var(--muted);font-size:.72rem;font-weight:700;text-transform:uppercase}.campaign-control select,.campaign-control input{min-width:0;border:1px solid var(--line);border-radius:10px;padding:11px 14px;color:var(--ink);background:#1b201c;font:inherit}
.time-control{display:flex;justify-content:space-between;align-items:end;gap:24px;padding:24px;border:1px solid var(--line);border-radius:18px;background:var(--panel)}.time-control p{margin-bottom:0;color:var(--muted)}.time-control form{display:grid;grid-template-columns:auto auto;gap:8px;align-items:center}.time-control label{color:var(--muted);font-size:.72rem;font-weight:700;text-transform:uppercase}.time-control select{min-width:150px;border:1px solid var(--line);border-radius:10px;padding:11px 14px;color:var(--ink);background:#1b201c;font:inherit}.time-control button{grid-column:1/-1}
.world-action{display:flex;justify-content:space-between;align-items:end;gap:24px;padding:24px;border:1px solid var(--line);border-radius:18px;background:rgba(217,180,111,.055)}.world-action p{margin-bottom:0;color:var(--muted)}.world-action form{display:grid;grid-template-columns:auto minmax(150px,1fr);gap:8px;align-items:center}.world-action label{color:var(--muted);font-size:.72rem;font-weight:700;text-transform:uppercase}.world-action select,.world-action input{border:1px solid var(--line);border-radius:10px;padding:11px 14px;color:var(--ink);background:#1b201c;font:inherit}.world-action button{grid-column:1/-1}
.world-strip{display:grid;grid-template-columns:1.5fr repeat(2,1fr);border:1px solid var(--line);border-radius:18px;overflow:hidden;background:rgba(255,255,255,.025)}.world-strip article{padding:20px;border-right:1px solid var(--line)}.world-strip article:last-child{border-right:0}.world-strip span,.stats span,footer span{display:block;margin-bottom:7px;color:var(--muted);font-size:.72rem;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.world-strip strong{font-family:Georgia,serif;font-size:1.35rem;font-weight:500}
section{margin-top:52px}.section-heading{margin-bottom:18px}.npc-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.npc-card{padding:22px;border:1px solid var(--line);border-radius:18px;background:var(--panel);box-shadow:0 18px 70px rgba(0,0,0,.18)}.npc-top{display:flex;justify-content:space-between;align-items:start;gap:12px;padding-bottom:22px;border-bottom:1px solid var(--line)}.role{margin-bottom:5px;color:var(--muted);font-size:.78rem;text-transform:capitalize}.location{flex:none;max-width:45%;border-radius:999px;padding:7px 10px;color:#cde0ce;background:rgba(143,174,145,.12);font-size:.75rem;text-align:center}.stats{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin:20px 0}.stats div{padding:12px;border-radius:12px;background:rgba(255,255,255,.035)}.knowledge span{color:var(--gold);font-size:.72rem;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.knowledge p{margin:6px 0 0;color:var(--muted);font-size:.86rem;line-height:1.5}
.chronicle ol{margin:0;padding:0;list-style:none;border-top:1px solid var(--line)}.chronicle li{display:grid;grid-template-columns:120px 1fr;gap:18px;padding:16px 4px;border-bottom:1px solid var(--line)}.chronicle time{color:var(--gold);font:.82rem ui-monospace,monospace}.chronicle p{margin:0;line-height:1.45}footer{display:flex;justify-content:space-between;gap:20px;margin-top:52px;padding-top:18px;border-top:1px solid var(--line);color:var(--muted);font-size:.76rem}code,pre{overflow-wrap:anywhere;color:#d6dfd5;font-family:ui-monospace,monospace}.empty-state{min-height:75vh;display:flex;flex-direction:column;align-items:flex-start;justify-content:center}.empty-state pre{max-width:100%;padding:18px;border:1px solid var(--line);border-radius:12px;background:var(--panel);white-space:pre-wrap}
@media(max-width:800px){.shell{width:min(100% - 22px,640px);padding-top:28px}.hero{align-items:start}h1{font-size:3.35rem}.world-strip{grid-template-columns:1fr 1fr}.world-strip article:first-child{grid-column:1/-1;border-bottom:1px solid var(--line)}.npc-grid{grid-template-columns:1fr}.campaign-control,.time-control,.world-action{display:block}.campaign-forms,.time-control form,.world-action form{margin-top:20px}section{margin-top:40px}}
@media(max-width:480px){.hero{display:block}.hero button{width:100%;margin-top:12px}.campaign-forms{grid-template-columns:1fr}.time-control form,.world-action form{grid-template-columns:1fr}.time-control button,.world-action button{grid-column:auto}.chronicle li{grid-template-columns:1fr;gap:6px}footer{display:block}}";
}
