<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\TessitoreGM.Core\TessitoreGM.Core.csproj" />
    <ProjectReference Include="..\TessitoreGM.Events\TessitoreGM.Events.csproj" />
    <ProjectReference Include="..\TessitoreGM.Narration\TessitoreGM.Narration.csproj" />
    <ProjectReference Include="..\TessitoreGM.World\TessitoreGM.World.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
