<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.1.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TessitoreGM.AiGm\TessitoreGM.AiGm.csproj" />
    <ProjectReference Include="..\..\src\TessitoreGM.Core\TessitoreGM.Core.csproj" />
    <ProjectReference Include="..\..\src\TessitoreGM.Events\TessitoreGM.Events.csproj" />
    <ProjectReference Include="..\..\src\TessitoreGM.Gm\TessitoreGM.Gm.csproj" />
    <ProjectReference Include="..\..\src\TessitoreGM.Memory\TessitoreGM.Memory.csproj" />
    <ProjectReference Include="..\..\src\TessitoreGM.Narration\TessitoreGM.Narration.csproj" />
    <ProjectReference Include="..\..\src\TessitoreGM.Npcs\TessitoreGM.Npcs.csproj" />
    <ProjectReference Include="..\..\src\TessitoreGM.World\TessitoreGM.World.csproj" />
  </ItemGroup>

</Project>
